email='gradproj20188@gmail.com'
password='elgraduationproject'
title='ResultsNumber1'
url='https://docs.google.com/spreadsheets/d/1ljKXNsuUElPpD1MagutM7zPrwyyG5XFIFk0cdldLWJQ/edit#gid=0'
sheet1_title='ResultsNumber1'
